### ISSUE TITLE
How to disable thriftpy's auto decoding?

### ISSUE THREAD

**Issue by cherrot** [wbolster/happybase#122] opened 2016-04-29 08:28 UTC
Recently I found that `thriftpy` would decode hbase keys and values automatically.  For example: 

```
conn = happybase.Connection('example.hbase.com')
table =  conn.table('some_table')
table.put('an_image', {'cf1:content': image_file.read()})
table.put('a_text', {'cf1:content': 'hello happybase!'})

print( type(table.row('an_image')[u'cf1:content']) ) # str
print( type(table.row('a_text')[u'cf1:content']) )  # unicode
```

Is there an elegant way to disable this feature?  Currently I'm doing like this: 

```
row = table.row('some_key')
content = row['cf1:content']
if isinstance(content, unicode):
    content = content.encode('utf-8')
```

**Comment by wbolster** [comment] 2016-04-29 08:52
yep, known problem with current `master`. the latest released version does not use `thriftpy` so it does not have this problem.

my request to fix this https://github.com/eleme/thriftpy/issues/190 was addressed, but only partially, so i filed https://github.com/eleme/thriftpy/issues/193 and fixed it with https://github.com/eleme/thriftpy/pull/194.

however, since upstream has not rolled a new release with this fix yet (request for that is https://github.com/eleme/thriftpy/issues/197), this issue remains for now. i've filed https://github.com/wbolster/happybase/issues/118 to track this.

:)

**Comment by wbolster** [comment] 2016-04-29 08:53
closing this as a duplicate of https://github.com/wbolster/happybase/issues/118

**Closed by wbolster** 2016-04-29 08:53 UTC
