### ISSUE TITLE
Method for checking whether table is enabled returns returns True for non-existent table

### ISSUE THREAD

**Issue by jaloren** [wbolster/happybase#91] opened 2015-05-11 13:43 UTC
If I call the is_table_enabled method on a non-existent table, the function returns true. I would expect the TableNotFound exception to be thrown. 

https://happybase.readthedocs.org/en/latest/api.html#happybase.Connection.is_table_enabled

**Comment by wbolster** [comment] 2015-05-11 13:53
Duplicate of #69.

I guess this is a HBase bug, not a Happybase issue, since Happybase simply delegates to the Thrift server.

**Closed by wbolster** 2015-05-11 13:53 UTC
