### ISSUE TITLE
Does anyone else get TTransportException with hbase 1.2.0?

### ISSUE THREAD

**Issue by csabaszilveszter** [wbolster/happybase#130] opened 2016-07-07 20:13 UTC
We use ```thrift==0.9.3```, ```happybase==0.9``` with ```Python 2.7.5```.
We used to have hbase 1.0 and have upgraded to 1.2.0 and since I get this after a few scans:
```
>>> import happybase
>>> hbase = happybase.Connection(host='sfleb1hdmap21.eb1.ecsna.com', port=9090)
07/07/16 14:15:20 DEBUG happybase.connection: Opening Thrift transport to sfleb1hdmap21.eb1.ecsna.com:9090
>>> for key, value in hbase.table('sometable').scan(row_prefix='some_row_prefix'):
...     print key, value
... 
07/07/16 14:16:13 DEBUG happybase.table: Opened scanner (id=9) on 'sometable'
07/07/16 14:16:13 DEBUG happybase.table: Closed scanner (id=9) on 'sometable' (2 returned, 2 fetched)
row1 {'cf:cn':'value1'}
row2 {'cf:cn':'value2'}
>>> # repeating the above works for usually 3 or 4 attempts, then
>>> for key, value in hbase.table('sometable').scan(row_prefix='some_row_prefix'):
...     print key, value
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/deploy/ecs-files_dev/lib/python2.7/site-packages/happybase/table.py", line 374, in scan
    self.name, scan, {})
  File "/home/deploy/ecs-files_dev/lib/python2.7/site-packages/happybase/hbase/Hbase.py", line 1919, in scannerOpenWithScan
    return self.recv_scannerOpenWithScan()
  File "/home/deploy/ecs-files_dev/lib/python2.7/site-packages/happybase/hbase/Hbase.py", line 1932, in recv_scannerOpenWithScan
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
  File "/home/deploy/ecs-files_dev/lib/python2.7/site-packages/thrift/protocol/TBinaryProtocol.py", line 126, in readMessageBegin
    sz = self.readI32()
  File "/home/deploy/ecs-files_dev/lib/python2.7/site-packages/thrift/protocol/TBinaryProtocol.py", line 206, in readI32
    buff = self.trans.readAll(4)
  File "/home/deploy/ecs-files_dev/lib/python2.7/site-packages/thrift/transport/TTransport.py", line 58, in readAll
    chunk = self.read(sz - have)
  File "/home/deploy/ecs-files_dev/lib/python2.7/site-packages/thrift/transport/TTransport.py", line 159, in read
    self.__rbuf = StringIO(self.__trans.read(max(sz, self.__rbuf_size)))
  File "/home/deploy/ecs-files_dev/lib/python2.7/site-packages/thrift/transport/TSocket.py", line 120, in read
    message='TSocket read 0 bytes')
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
07/07/16 14:40:25 DEBUG happybase.connection: Closing Thrift transport to sfleb1hdmap21.eb1.ecsna.com:9090
```

**Comment by Pils19** [comment] 2016-08-07 12:27
Hey, i get this error as well. I use Happybase and Hbase for my Bachelor thesis. I guess maybe the Transport protocol of the Thriftclient from Happybase does not match fully the protocol version ?!? I hope someone else has an idea how to fix this? Or maybe you fixed this science you posted the issue. If i will find i solution i will let you know about it.

**Comment by wbolster** [comment] 2016-08-10 15:48
happybase has recently switched to another thrift _client_ library (thriftpy) in the `master` branch, but if the problem is at the server side you're out of luck unfortunately.

closing this issue since it does not seem something happybase can fix...

**Closed by wbolster** 2016-08-10 15:48 UTC

**Comment by stevealx** [comment] 2017-04-14 01:33
FYI, this seems to be related to [HBASE-14926](https://issues.apache.org/jira/browse/HBASE-14926)  We ran into this while testing CDH 5.10.1.

We increased from 60s to 1 day to handle our short-lived apps, and changed our long-running apps to close connections after finishing operations.  So far, so good, for what it's worth.

The timeout value is in ms, if you decided to change it.

**Comment by kadhriesh** [comment] 2018-11-28 16:39
I am having the same issue with happy base 1.0.0 and hbase 2.0.2 can some help to resolve this issue

**Comment by qiutianhao** [comment] 2019-01-18 05:42
you should do this: 
/etc/hbase/conf/hbase-site.xml
```
  <property>
    <name>hbase.thrift.server.socket.read.timeout</name>
    <value>0</value>
  </property>
```

**Comment by niboshi** [comment] 2021-01-19 04:55
For anyone coming to this issue because of the same mistake as mine:
Missing column family qualifier (`cf:`) caused this error.
